name: Run nf-raffle Pipeline

on:
  workflow_dispatch:
    inputs:
      email:
        description: "Email address for raffle entry"
        required: true
        default: "fake.name@fakeplace.com"
        type: string
      event:
        description: "Event name"
        required: false
        type: string
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "latest"

      - name: Run nf-raffle pipeline
        run: |
          nextflow run . \
            --email "${{ github.event.inputs.email || 'fake.name@fakeplace.com' }}" \
            ${{ github.event.inputs.event && format('--event {0}', github.event.inputs.event) || '' }} \
            --outdir results

      - name: Upload results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pipeline-results
          path: results/
          retention-days: 7

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: nextflow-logs
          path: |
            .nextflow.log
            work/
          retention-days: 7
